language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

after_success:
  - npm run coverage
  - npm i codecov
  - codecov -f coverage/coverage.json

notifications:
  email:
    on_success: never
